### ISSUE TITLE
examples/threejs.html not work in the latest version

### ISSUE THREAD

**Issue by tornadory** [jagenjo/litegl.js#1]
Hi Jagenjo,

before I ever tested and threejs example works well, but when I updated repo these days it won't work right now, no error but many warnings.

"three.js:4505 WebGL: INVALID_OPERATION: uniformMatrix4fv: location is not from current program"

**Comment by jagenjo** [comment]
with which example do you get that error? it seems that you are passing something wrong to Three.JS
