### ISSUE TITLE
How can I use vertex colors?

### ISSUE THREAD

**Issue by cx20** [jagenjo/litegl.js#4]
I learned that `litegl.js` is a library developed by forking `lightgl.js`.
I tried to port a sample of `lightgl.js` using vertex colors to a version using `litegl.js`.
However, I did not know how to use vertex colors in `litegl.js`.
Is it possible to use vertex colors in this library?

The following is a sample using vertex color in `lightgl.js`.
http://jsdo.it/cx20/br0W

![image](https://user-images.githubusercontent.com/1833979/52448636-e2578580-2b77-11e9-9565-b2c5e4ffd28d.png)

**Comment by jagenjo** [comment]
yes, it is supported but litegl removes the fixed pipeline behaviour from lightgl, that means you have to code your own shaders.

you can define the mesh as:

```var mesh = GL.Mesh.load({ vertices:[ 0,0,0,  10,10,0,  20,0,0 ], colors: [ 1,0,0,1, 0,1,0,1, 0,0,1,1 ]});```

but then you have to create your own shaders that receives the ```varying vec4 a_color``` by vertex.

**Comment by cx20** [comment]
@jagenjo Thanks to your advice I was able to port the samples.
Below is a sample of vertex color by `litegl.js`.

[litegl.js  + Squarecase result:](http://jsdo.it/cx20/GeCE)
![image](https://user-images.githubusercontent.com/1833979/52487686-7e799f00-2c01-11e9-823c-56dbdd6fc237.png)

After creating some samples, I will add this library to the WebGL library list.
https://qiita.com/cx20/items/0fa19c96aa6470d98807

**Comment by jagenjo** [comment]
great work! having a list with all webgl engines is very handy

**Comment by cx20** [comment]
I created 4 samples and added litegl.js to the WebGL list.
https://qiita.com/cx20/items/0fa19c96aa6470d98807#using-vbo
![image](https://user-images.githubusercontent.com/1833979/52515467-4a34cb80-2c5f-11e9-80bd-aa9855dc46bd.png)
