### ISSUE TITLE
Possible memory leak ?

### ISSUE THREAD

**Issue by itamayo** [jagenjo/litegl.js#6]
Hi !

I'm trying to develop video texture plane but I have some problems, since GPU memory increase until crash:

```javascript
		 gl.ondraw = function()
				 {

					 if (_stream ){
						 first =false;
						 let texture = Texture.fromVideo(_stream,{minFilter: gl.NEAREST});
						 texture.bind(0);
						 shader.uniforms({
								 u_color: [1,1,1,1],
								 u_model: model,
								 u_texture: 0,
								 u_mvp: mvp
							 }).draw(mesh);


				 }
			 }
```
What am I doing wrong ?

Thanks !

**Comment by jagenjo** [comment]
You are creating a video texture every frame.
You must create the texture outside the loop and update it every frame using the method:
texture.uploadImage( _stream );
